### PR TITLE
Added Readme.md and configured .eslint file

### PR DESCRIPTION
**Pull request by sameercodes**
Added Readme.md and configured .eslint file

### CODE REVIEW

**Comment by ashokdey** [comment]
Thanks, @sameercodes! I will complete the rest of the README soon. 😊

**Comment by sameercodes** [comment]
Hi @ashokdey instead of writing some eslint configs to avoid error in the code, i rewrited the rules on .eslintrc.js file, and also it is good to write absolute imports come before relative imports?

[Refer this:](https://stackoverflow.com/questions/47734886/why-should-absolute-imports-come-before-relative-imports)

**Comment by sameercodes** [comment]
What about review?

**Comment by ashokdey** [comment]
> What about review?

Going to merge this. How about writing test cases for the services? Would you like to do that? I will then setup TravisCI for CI

**Comment by ashokdey** [comment]
> write absolute imports come before relative imports

I prefer ```write absolute imports come before relative imports```. It is a clean approach

**Pull request merged**
